### ISSUE TITLE
Sphinx problem

### ISSUE THREAD

**Issue by mtsteven** [spob/openmind#1] opened 2010-09-29 11:11 UTC
Rake doesn't seem to run.

I have installed:
Sphinx 0.9.9
thinking-sphinx (1.3.20)

Error shown:
# rake db:migrate --trace

(in /_/httpdocs/openmind)
*_ Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
Observers are disabled. This should be the case if you've not yet run
your initial migration. Once the initial migration is complete, you should
enable observers by copy the file:
/_/httpdocs/openmind/config/observe.no.txt
to
/_/httpdocs/openmind/config/observe.txt
Requiring REXML
*\* Execute db:migrate
==  SeedUser: migrating =======================================================
rake aborted!
An error has occurred, all later migrations canceled:

undefined method `delta=' for #<User:0xb7038470>
/*/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:255:in`method_missing'
/usr/lib/ruby/gems/1.8/gems/thinking-sphinx-1.3.20/lib/thinking_sphinx/deltas/default_delta.rb:23:in `toggle'
/usr/lib/ruby/gems/1.8/gems/thinking-sphinx-1.3.20/lib/thinking_sphinx/active_record/delta.rb:35:in`toggle_delta'
/_/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `send'
/_/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `evaluate_method'
/*/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/callbacks.rb:166:in`call'
/_/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/callbacks.rb:93:in `run'
/_/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/callbacks.rb:92:in `each'
/*/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/callbacks.rb:92:in`send'
/_/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/callbacks.rb:92:in `run'
/_/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/callbacks.rb:276:in `run_callbacks'
/*/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/callbacks.rb:344:in`callback'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/callbacks.rb:249:in `create_or_update'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/base.rb:2556:in `save_without_validation!'
/*/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/validations.rb:1019:in`save_without_dirty!'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/dirty.rb:87:in `save_without_transactions!'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/transactions.rb:200:in `save!'
/*/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in`transaction_without_callback'
/usr/lib/ruby/gems/1.8/gems/after_commit-1.0.8/lib/after_commit/connection_adapters.rb:12:in `transaction'
/*/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/transactions.rb:182:in`transaction'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/transactions.rb:200:in `save!'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
/*/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/transactions.rb:200:in`save!'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/validations.rb:990:in `create!'
/_/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/option_merger.rb:20:in `__send__'
/*/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/option_merger.rb:20:in`method_missing'
./db/migrate//010_seed_user.rb:8:in `up_without_benchmarks'
/*/httpdocs/openmind/vendor/rails/activesupport/lib/active_support/core_ext/object/misc.rb:78:in`with_options'
./db/migrate//010_seed_user.rb:4:in `up_without_benchmarks'
/*/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:282:in`send'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:282:in `migrate'
/usr/lib/ruby/1.8/benchmark.rb:293:in`measure'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:282:in `migrate'
(__DELEGATION__):2:in`**send**'
(**DELEGATION**):2:in `migrate'
/*/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:486:in`migrate'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:562:in `call'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:562:in `ddl_transaction'
/*/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:485:in`migrate'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:472:in `each'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:472:in `migrate'
/*/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:400:in`up'
/_/httpdocs/openmind/vendor/rails/activerecord/lib/active_record/migration.rb:383:in `migrate'
/_/httpdocs/openmind/vendor/rails/railties/lib/tasks/databases.rake:116
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in`load'
/usr/bin/rake:19

What I don't seem to understand is some lines on:
sphinx.yml: bin_path: 'c:/sphinx/bin' ? (i've removed this line)
development.sphinx.conf: contains a lot of hardcoded information (path, mysql account,...)

Does this has anything to do with the problem?

**Comment by spob** [comment] 2010-10-01 10:49
Sorry that you've run into this issue. It's a bit of a catch-22 and I'll have to think about how I will resolve it.

The problem is that the rails is trying to update the search engine (thinking sphinx) which is looking for the column called delta. Since the search engine was added later, that column was added later...

As a short term solution, my suggestion is temporarily change the line:

 set_property :delta => true

to 
 set_property :delta => false

then run your migration, then change that back.

**Comment by spob** [comment] 2010-10-22 14:11
This should be fixed with my latest commits. I moved populating seed data out of the migration files and into a db:seed rake task. See the latest manual for further details.

**Comment by mtsteven** [comment] 2010-10-22 14:18
OK, thank you. I'll try it out asap.

**Closed as completed** 2010-10-22 21:11 UTC
